import React from 'react'

import Head from 'next/head'

import { getGlobalLayout } from '@/components/layout'
import { ProfilePage } from '@/modules/profile-modules/profile-module'
import { NextPageWithLayout } from '@/pages/_app'

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Inctagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfilePage />
    </>
  )
}

Home.getLayout = getGlobalLayout
export default Home
