import Head from 'next/head'

import { getLayoutWithHeader } from '@/components/layout/LayoutWithHeader/LayoutWithHeader'
import { NextPageWithLayout } from '@/pages/_app'
import PageLogin from '@/pages/auth/login'

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Inctagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLogin />
    </>
  )
}

Home.getLayout = getLayoutWithHeader
export default Home
