import { useEffect } from 'react'

import Head from 'next/head'
import { useRouter } from 'next/router'

import { getLayoutWithHeader } from '@/components/layout'
import { LoginPage, useMeQuery } from '@/modules/auth-modules/login-module'
import { NextPageWithLayout } from '@/pages/_app'

const Home: NextPageWithLayout = () => {
  const { push } = useRouter()

  const { data } = useMeQuery()
  const userName = data && data.data

  useEffect(() => {
    if (userName) {
      push('/profile')
    }
  }, [userName])

  return (
    <>
      <Head>
        <title>Inctagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage />
    </>
  )
}

Home.getLayout = getLayoutWithHeader
export default Home
